python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_PLAIN --template SatacMissionBase_v1.6.2 --cloud LIGHT_SCATTERED_1  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date 201612241245 --bda false --airport Tbilishi,Sukhumi
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_PLAIN2 --template SatacMissionBase_v1.6.2 --cloud LIGHT_RAIN_1  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date 201609180705 --bda false --airport Tbilishi,Sukhumi
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_PLAIN3 --template SatacMissionBase_v1.6.2 --cloud BROKEN5  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date 201609271300 --bda false --airport Tbilishi,Sukhumi
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_CRIMEA --template SatacMissionBase_v1.6.2 --cloud clear  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date all --bda false --ccspos "31493,-12672"
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_SEA   --template SatacMissionBase_v1.6.2 --cloud clear  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date all --bda false --airport Kobuleti,Sukhumi
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_SEA   --template SatacMissionBase_v1.6.2 --cloud clear  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date all --bda false --airport Batumi,Sochi
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_MNT1  --template SatacMissionBase_v1.6.2 --cloud SCATTERED_1  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date 201609051400 --bda false --airport Sochi,Mozdok
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_MNT2  --template SatacMissionBase_v1.6.2 --cloud LIGHT_SCATTERED1  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date 201610051230 --bda false --airport Sochi,Mozdok
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_MNT3  --template SatacMissionBase_v1.6.2 --cloud OVERCAST_AND_RAIN_2  --wind 0.0 --distance 100 --posJitter 0 --angleJitter 0 --AWACSdistance 135 --date 201610050830 --bda false --airport Sochi,Mozdok
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_MNT3  --template SatacMissionBase_v1.6.2 --cloud all --wind 0.0 --distance 100 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda false --airport Batumi,Tbilishi
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_RND1 --template SatacMissionBase_v1.6.2 --cloud all  --wind 0.0 --distance 100 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda false
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_RND2 --template SatacMissionBase_v1.6.2 --cloud all  --wind 0.0 --distance 100 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda false
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_RND3 --template SatacMissionBase_v1.6.2 --cloud all  --wind 0.0 --distance 100 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda false
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_RND4 --template SatacMissionBase_v1.6.2 --cloud all  --wind 0.0 --distance 100 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda false
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_MULTI --template SatacMissionBase_v1.6.2 --cloud all  --wind 0.0 --distance 100 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda false --multisector true

python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_30nm_PLAIN --template SatacMissionBase_v1.6.2 --cloud clear --wind 0.0 --distance 30 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --alt 8000 --bda ture --notank true --airport Tbilishi,Sukhumi
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_30nm_CRIMEA --template SatacMissionBase_v1.6.2 --cloud clear --wind 0.0 --distance 30 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --alt 8000 --bda ture --notank true --ccspos "31493,-12672"
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_30nm_SEA --template SatacMissionBase_v1.6.2 --cloud clear --wind 0.0 --distance 30 --posJitter 0 --angleJitter 0 --AWACSdistance 140 --date all --alt 8000 --bda ture --notank true --airport Batumi,Sochi
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_MNT1  --template SatacMissionBase_v1.6.2 --cloud clear  --wind 0.0 --distance 30 --posJitter 0 --angleJitter 0 --AWACSdistance 140 --date all --alt 8000 --bda true --notank true --airport Sochi,Mozdok
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_MNT2  --template SatacMissionBase_v1.6.2 --cloud all  --wind 0.0 --distance 30 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --alt 8000 --bda true --notank true --airport Sochi,Mozdok
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_30nm_RND1   --template SatacMissionBase_v1.6.2 --cloud all --wind 0.0 --distance 30 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --alt 8000 --bda ture --notank true --airport all
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_30nm_RND2   --template SatacMissionBase_v1.6.2 --cloud all --wind 0.0 --distance 30 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --alt 8000 --bda ture --notank true --airport all
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_30nm_RND3   --template SatacMissionBase_v1.6.2 --cloud all --wind 0.0 --distance 30 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --alt 8000 --bda ture --notank true --airport all
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_30nm_RND4   --template SatacMissionBase_v1.6.2 --cloud all --wind 0.0 --distance 30 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --alt 8000 --bda ture --notank true --airport all
python3 SumouFieldGenerator.py --theatre Ca --fileprefix BVR_30nm_MULTI   --template SatacMissionBase_v1.6.2 --cloud clear --wind 0.0 --distance 30 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --alt 8000 --bda ture --notank true --multisector true

python3 SumouFieldGenerator.py --theatre Ca --fileprefix WVR_PLAIN --template Guns_WVRMissionBase_v1.8.1 --cloud clear --wind 0.0 --distance 15 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda true --airport Tbilishi,Sukhumi
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix WVR_CRIMEA --template Guns_WVRMissionBase_v1.8.1 --cloud clear --wind 0.0 --distance 15 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda true --ccspos "31493,-12672"
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix WVR_MNT1 --template Guns_WVRMissionBase_v1.8.1 --cloud clear --wind 0.0 --distance 15 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda true --airport Nalchik,Senaki
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix WVR_RND1 --template Guns_WVRMissionBase_v1.8.1 --cloud clear --wind 0.0 --distance 15 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda true --airport all
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix WVR_RND2 --template Guns_WVRMissionBase_v1.8.1 --cloud clear --wind 0.0 --distance 15 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda true --airport all
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix WVR_RND3 --template Guns_WVRMissionBase_v1.8.1 --cloud all --wind 0.0 --distance 15 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda true --airport all
# python3 SumouFieldGenerator.py --theatre Ca --fileprefix WVR_RND4 --template Guns_WVRMissionBase_v1.8.1 --cloud all --wind 0.0 --distance 15 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda true --airport all
python3 SumouFieldGenerator.py --theatre Ca --fileprefix WVR_MULTI --template Guns_WVRMissionBase_v1.8.1 --cloud clear --wind 0.0 --distance 15 --posJitter 20 --angleJitter 20 --AWACSdistance 140 --date all --bda true --multisector true